name: build-mac

on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-10.15
    steps:
    - name: checkout sources
      uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/Qt
        key: ${{ runner.os }}-QtCache-5.15.0

    - name: Download and install Qt
      uses: jurplel/install-qt-action@v2 
      with:
        version: '5.15.0'
        dir: ${{github.workspace}}
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        target: 'desktop'

    - name: create build dir
      run: mkdir ${{github.workspace}}/build

    # - name: debug output
    #   run: |
    #     echo ls GITHUB_WORKSPACE ${{github.workspace}}
    #     ls ${{github.workspace}}
    #     echo ls Qt5_DIR $Qt5_DIR ${{ env.Qt5_DIR }}
    #     ls $Qt5_DIR
    #     echo ls Qt5_DIR/lib $Qt5_DIR/lib
    #     ls $Qt5_DIR/lib
    #     echo ls Qt5_DIR/lib/cmake $Qt5_DIR/lib/cmake
    #     ls $Qt5_DIR/lib/cmake
    #     echo ls Qt5_DIR/lib/cmake/Qt5 $Qt5_DIR/lib/cmake/Qt5
    #     ls $Qt5_DIR/lib/cmake/Qt5

    - name: cmake generate/configure
      working-directory: ${{github.workspace}}/build
      run: cmake -GXcode ..

    - name: cmake build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --target ALL_BUILD --config Debug

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binary
        path: build/Debug/