name: build-mac

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install-qt:
    runs-on: macos-10.15
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Download and install Qt
      shell: bash
      env:
        QT_PASSWORD: ${{ secrets.QT_TEST }}
      run: |
        ls $GITHUB_WORKSPACE
        env
