name: build-mac

on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-10.15
    steps:
    - name: checkout sources
      uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: $GITHUB_WORKSPACE/Qt
        key: ${{ runner.os }}-QtCache-5.12.9

    - name: Download and install Qt
      uses: jurplel/install-qt-action@v2
      if: 
      with:
        version: '5.12.9'
        dir: $GITHUB_WORKSPACE
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        target: 'desktop'

    - name: create build dir
      run: mkdir $GITHUB_WORKSPACE/build

    - name: debug output
      run: |
        echo ls GITHUB_WORKSPACE $GITHUB_WORKSPACE
        ls $GITHUB_WORKSPACE
        echo ls Qt5_DIR $Qt5_DIR
        ls $Qt5_DIR
        echo ls Qt5_DIR/lib $Qt5_DIR/lib
        ls $Qt5_DIR/lib

    - name: cmake generate/configure
      working-directory: build
      run: cmake -GXcode ..

    - name: cmake build
      working-directory: build
      run: cmake --build . --target ALL_BUILD