name: build-mac

on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-10.15
    steps:
    - name: checkout sources
      uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/Qt
        key: ${{ runner.os }}-QtCache-5.15.0

    - name: Download and install Qt
      uses: jurplel/install-qt-action@v2 
      with:
        version: '5.15.0'
        dir: ${{github.workspace}}
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        target: 'desktop'

    - name: create build dir
      run: mkdir ${{github.workspace}}/build

    - name: import code signing cert
      uses: apple-actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.CERT_P12 }}
        p12-password: ${{ secrets.CERT_P12_PASSWORD }}

    - name: cmake generate/configure
      working-directory: ${{github.workspace}}/build
      run: cmake -GXcode ..

    - name: cmake build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --target ALL_BUILD --config Debug

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binary
        path: build/Debug/