name: build-mac

on:
  workflow_dispatch:

jobs:
  install-qt:
    runs-on: macos-10.15
    steps:
    - name: checkout sources
      uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: $RUNNER_WORKSPACE/Qt
        key: ${{ runner.os }}-QtCache

    - name: Download and install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.9'
        dir: $RUNNER_WORKSPACE
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        target: 'desktop'

    - name: cmake generate/configure
      working-directory: $RUNNER_WORKSPACE/build
      run: cmake -GXcode $GITHUB_WORKSPACE

    - name: cmake build
      working-directory: $RUNNER_WORKSPACE/build
      run: cmake --build . --target ALL_BUILD

