name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        mkdir build
        mkdir symbols
        echo Add other actions to build > build/binary
        echo test, and deploy your project > symbols/debug_symbols
    - name: Run cmake -h
      run: cmake -h
    - name: upload artifact1
      uses: actions/upload-artifact@v2
      with:
        name: binary
        path: build/
    - name: upload artifact2
      uses: actions/upload-artifact@v2
      with:
        name: debug_symbols
        path: symbols
